name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
  - title: '🔧 Refactoring'
    labels:
      - 'refactor'
      - 'refactoring'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'tests'
      - 'testing'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🏗️ Build & CI'
    labels:
      - 'build'
      - 'ci'
      - 'cd'
      - 'workflow'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '🧹 Chore'
    labels:
      - 'chore'
      - 'maintenance'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to all contributors who made this release possible!

  $CONTRIBUTORS

autolabeler:
  - label: 'feat'
    title:
      - '/^feat(\(.+\))?.+/i'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?.+/i'
  - label: 'refactor'
    title:
      - '/^refactor(\(.+\))?.+/i'
  - label: 'docs'
    title:
      - '/^docs(\(.+\))?.+/i'
  - label: 'test'
    title:
      - '/^test(\(.+\))?.+/i'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?.+/i'
  - label: 'build'
    title:
      - '/^build(\(.+\))?.+/i'
  - label: 'ci'
    title:
      - '/^ci(\(.+\))?.+/i'
  - label: 'perf'
    title:
      - '/^perf(\(.+\))?.+/i'
  - label: 'breaking'
    title:
      - '/BREAKING CHANGE/i'